local colors  = {
  bg          = '#2d323b',
  section_bg  = '#3e4452',
  fg          = '#abb2bf',
  aqua        = Aqua[1],
  black       = Black[1],
  blue        = Blue[1],
  dark_blue   = DarkBlue[1],
  cyan        = Cyan[1],
  dark_cyan   = DarkCyan[1],
  green       = Green[1],
  dark_green  = DarkGreen[1],
  grey        = Grey[1],
  magenta     = Magenta[1],
  orange      = Orange[1],
  dark_orange = DarkOrange[1],
  purple      = Purple[1],
  red         = Red[1],
  dark_red    = DarkRed[1],
  violet      = Violet[1],
  white       = White[1],
  yellow      = Yellow[1],
  dark_yellow = DarkYellow[1],
}

return colors
